server:
  port: ${PORT:${SERVICE_PORT:0}}

spring:
  data:
    mongodb:
      uri: mongodb+srv://dbuser:Passw0rd11235@cluster0.abvys.mongodb.net/RetailClientDB?retryWrites=true&w=majority

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.default-zone: http://localhost:8761/eureka

constants:
  url:
    server: http://localhost:8080

#server.port=${PORT:${SERVICE_PORT:0}}
#spring.data.mongodb.uri=mongodb+srv://dbuser:Passw0rd11235@cluster0.abvys.mongodb.net/RetailClientDB?retryWrites=true&w=majority
#eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.default-zone=http://localhost:8761/eureka